name: Run tests and upload coverage

on:
  push:
    branches:
      - "feature/**"
      - "refactor/**"
      - "fix/**"
      - "main"

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v4.0.0
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@968872560f81e7bdde9272853e65f2507c0eca7c # v5.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
