name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      security-events: write
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v4.0.0

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod

      - name: Download Go dependencies
        run: go mod download

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Snyk Code test (SARIF)
        run: snyk code test --sarif-file-output=snyk-code.sarif
        continue-on-error: true

      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects
        continue-on-error: true

      - name: Upload result to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4
        with:
          sarif_file: snyk-code.sarif
